version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: devsof_local_django
    volumes:
      - .:/app
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file: .env
    ports:
      - "8000:8000"
      - "587:587"
      - "25:25"
    command: /start

  redis:
    image: "redis:latest"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  celeryworker:
    <<: *django
    image: devsof_local_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: devsof_local_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: devsof_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
    depends_on:
      - redis
      - celeryworker
