# Generated by Django 4.1.3 on 2023-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='latitud',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='longitud',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Longitud'),
        ),
    ]
