# Generated by Django 4.1.3 on 2023-01-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contratos_latitud_alter_contratos_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo'), ('3', 'Suspendido')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
