# Generated by Django 4.1.3 on 2023-01-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contratos_estado_de_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='sericios',
            new_name='servicios',
        ),
    ]
