# Generated by Django 4.1.3 on 2023-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_rename_sericios_contratos_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='fecha_instalacion',
            field=models.DateTimeField(default='2023-01-18', help_text='Fecha y hora de instalación', verbose_name='Fecha de instalación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratos',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo'), ('3', 'Suspendido')], default='2', max_length=1, verbose_name='Estado'),
        ),
    ]
