name: Test APP

on:
  push:
    branches: 
      - "42-github-actions-test"
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "local-db.yml"
        down-flags: "--volumes"
        services: |
          django
          db
          adminer

    - name: Build the stack
      run:  docker-compose -f local-db.yml build

    - name: Run Tests
      run: docker compose -f local-db.yml run --rm django pytest
