# Generated by Django 4.1.3 on 2022-12-19 05:12

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('estado', models.BooleanField(default=True, help_text='Ayuda a saber si la factura esta activa o inactiva', verbose_name='Estado')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de expedcion')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('total_pago', models.IntegerField(max_length=20, verbose_name='Total a pagar')),
                ('valor_pendiente_pago', models.IntegerField(max_length=20, verbose_name='Valor pendiente de pago')),
                ('porcentaje_pago', models.BigIntegerField(max_length=builtins.any, verbose_name='Porcentaje de pago')),
                ('valor_recargo', models.IntegerField(max_length=20, verbose_name='Valor de recargo')),
                ('recargo', models.BooleanField(default=False, help_text='ayuda a saber si se le aplica recargo o no', verbose_name='Recargo')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'db_table': 'factura',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
