# Generated by Django 4.1.3 on 2023-01-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(choices=[('1', 'KILOVATIO HORA'), ('2', 'METROS CÚBICOS')], max_length=1, verbose_name='Unidad de medida')),
                ('valor_unitario', models.FloatField(verbose_name='Valor unitario')),
                ('dia_de_corte', models.IntegerField(verbose_name='Día de corte')),
                ('porcentaje_recargo_mora', models.FloatField()),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'servicios',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
