# Generated by Django 4.1.3 on 2023-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='porcentaje_recargo_mora',
            field=models.FloatField(verbose_name='Porcentaje de recargo por mora'),
        ),
    ]
