# Generated by Django 4.1.3 on 2023-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicios_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='unidad_medida',
            field=models.CharField(choices=[('1', 'KILOVATIOS / HORA'), ('2', 'METROS CÚBICOS')], max_length=1, verbose_name='Unidad de medida'),
        ),
    ]
