# Generated by Django 4.1.3 on 2023-01-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicios_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='dia_de_corte',
        ),
    ]
