# Generated by Django 4.1.3 on 2023-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_remove_servicios_dia_de_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='porcentaje_recargo_mora',
            field=models.FloatField(null=True, verbose_name='Porcentaje de recargo por mora'),
        ),
    ]
