# Generated by Django 4.1.3 on 2023-01-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_configuracionesfacturacion_and_more'),
        ('servicios', '0006_alter_servicios_porcentaje_recargo_mora'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConsumoServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('lectura', models.BigIntegerField(blank=True, null=True, verbose_name='Lectura')),
                ('data_sent', models.JSONField(blank=True, null=True, verbose_name='Informacion enviada en peticion .')),
                ('data_received', models.JSONField(blank=True, null=True, verbose_name='Informacion obtenida en peticion.')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturas')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
            options={
                'verbose_name': 'log_consumo_servicios',
                'verbose_name_plural': 'log_consumo_servicios',
                'db_table': 'log_consumo_servicios',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
