# Generated by Django 4.1.3 on 2023-01-31 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_logconsumoservicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logconsumoservicios',
            options={'get_latest_by': 'created', 'managed': True, 'ordering': ['-created', '-updated'], 'verbose_name': 'log_consumo_servicios', 'verbose_name_plural': 'log consumo servicios'},
        ),
    ]
