# Generated by Django 4.1.3 on 2023-01-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_facturas_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('fecha_vigencia_inicio', models.DateTimeField(verbose_name='Fecha inicio de vigencia')),
                ('fecha_vigencia_fin', models.DateTimeField(verbose_name='Fecha fin de vigencia')),
                ('valor', models.FloatField(default=0, help_text='Valor pagado por la publicidad', verbose_name='Valor')),
                ('imagen', models.ImageField(upload_to='uploads/publicidad/', verbose_name='Imagen')),
                ('seccion_factura', models.CharField(choices=[('A', 'Seccion A'), ('B', 'Seccion B'), ('C', 'Seccion C')], default='A', max_length=1, verbose_name='Seccion Factura')),
            ],
            options={
                'verbose_name': 'publicidad',
                'verbose_name_plural': 'publicidades',
                'db_table': 'publicidad',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
