# Generated by Django 4.1.3 on 2023-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_publicidad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='imagen',
            field=models.ImageField(upload_to='uploads/publicidad/%Y/%m/%d/', verbose_name='Imagen'),
        ),
    ]
