# Generated by Django 4.1.3 on 2023-01-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_alter_publicidad_seccion_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionesFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('dia_de_corte', models.IntegerField(verbose_name='Día de corte')),
                ('porcentaje_recargo_mora', models.FloatField(verbose_name='Porcentaje de recargo por mora general')),
            ],
            options={
                'verbose_name': 'configuraciones_facturacion',
                'verbose_name_plural': 'configuraciones_facturacion',
                'db_table': 'configuraciones_facturacion',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='porcentaje_recargo',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='porcentaje_recargo',
            field=models.BigIntegerField(default=0, verbose_name='Porcentaje de cargo'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='total_a_pagar',
            field=models.IntegerField(default=0, verbose_name='Total a pagar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='valor_recargo',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='total_a_pagar',
            field=models.IntegerField(default=0, verbose_name='Total a pagar'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='valor_pendiente_pago',
            field=models.FloatField(default=0, verbose_name='Valor pendiente de pago'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='valor_recargo',
            field=models.IntegerField(default=0, verbose_name='Valor de recargo'),
        ),
    ]
