# Generated by Django 4.1.3 on 2023-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_configuracionesfacturacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_expedicion',
            field=models.DateTimeField(verbose_name='Fecha de expedición'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha_vencimiento',
            field=models.DateTimeField(verbose_name='Fecha de vencimiento'),
        ),
    ]
