# Generated by Django 4.1.3 on 2023-05-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_pagosfactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('seccion_factura', models.CharField(choices=[('A', 'Seccion A'), ('B', 'Seccion B'), ('C', 'Seccion C'), ('OTRO', 'Otro')], max_length=4, verbose_name='Seccion Factura')),
                ('valor', models.FloatField(default=0, help_text='Valor definido para la sección.', verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'seccion_factura',
                'verbose_name_plural': 'secciones de factura',
                'db_table': 'seccion_factura',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='publicidad',
            name='seccionfactura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.seccionfactura'),
        ),
    ]
