# Generated by Django 4.1.3 on 2023-05-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0012_seccionfactura_publicidad_seccionfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionfactura',
            name='valor',
            field=models.FloatField(help_text='Valor definido para la sección.', verbose_name='Valor'),
        ),
    ]
