# Generated by Django 4.1.3 on 2023-05-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('facturas', '0013_alter_seccionfactura_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosfactura',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bancos.bancos'),
        ),
    ]
