name: Test APP

on:
  push:
    branches: 
      - "main"
      - "42-github-actions-test"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build containers
      run:  docker-compose -f local-db.yml up --build -d

    - name: Run Tests
      run: docker-compose -f local-db.yml run --rm django pytest

    - name: Stop containers
      run: docker-compose -f local-db.yml down
