name: Test APP

on:
  push:
    branches: 
      - "main"
      - "42-github-actions-test"

env:
  REGISTRY: zethoc
  IMAGE_NAME: devsof2-nrgx-backend

jobs:
  # test:
    # runs-on: ubuntu-latest
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # # - name: Build containers
    # #   run:  docker-compose -f local-db.yml up --build -d

    # - name: Run Tests
    #   run: docker-compose -f local-db.yml run --rm django pytest

    # # - name: Stop containers
    # #   run: docker-compose -f local-db.yml down


  trivy-security:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./compose/local/django/

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          file: compose/local/django/Dockerfile

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  build-docker:
    runs-on: ubuntu-latest
    needs: trivy-security
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          file: compose/local/django/Dockerfile