name: Workflow Testing

on:
  push:
    branches: 
      - "testing"

env:
  REGISTRY: zethoc
  IMAGE_NAME: devsof2-nrgx-backend-testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Tests
      run: docker-compose -f local-db.yml run --rm django pytest

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          file: compose/local/django/Dockerfile

  deploy-aws:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Save SSH private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Set permissions for SSH private key
        run: chmod 600 ~/.ssh/id_rsa

      - name: Update known hosts
        run: ssh-keyscan "${{ secrets.IP_REMOTE }}" >> ~/.ssh/known_hosts

      - name: Connect to EC2 and execute commands
        run: |
          ssh -i ~/.ssh/id_rsa "${{ secrets.USER_REMOTE }}"@"${{ secrets.IP_REMOTE }}" "docker pull zethoc/devsof2-nrgx-backend && docker stop nrgx-testing && docker container run --rm -it --name nrgx-testing -p 8001:8000 --env-file .env -d zethoc/devsof2-nrgx-backend:latest && exit"
  